language: objective-c
osx_image: xcode8
sudo: false

before_install:
  - gem install --no-document cocoapods xcpretty

script:
  - set -o pipefail; xcodebuild -workspace *.xcworkspace -scheme "Hamcrest-macOS" build test | xcpretty -c
  - set -o pipefail; xcodebuild -workspace *.xcworkspace -scheme "Hamcrest-iOS" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=latest,name=iPhone 7" build test | xcpretty -c
  - pod lib lint SwiftHamcrest.podspec
